// ignore_for_file: file_names

class Globle {
  static int index = 0;
  static List planetDetails = [
    {
      "id": 1,
      "name": "Mercury",
      "color": "Slate Gray",
      "Discovery": "Known to the ancient Greeks and visible to the naked eye",
      "Diameter": "4,878 Km",
      "Orbit": "88 Earth Days",
      "Day": "58.6 Earth Days",
      "Number of moons": "0",
      "Distance from Sun": "68.946 Million Km",
      "Volume": "60.8 Billion Cubic Km",
      "Mass": "3.285 * 10^23 Kg",
      "Planet type": "Terrestrial Planet",
      "Surface temperature": "430° C",
      "images": "images/Mercury.png",
      "Discription":
          "Mercury is the closest planet to the sun and the smallest planet in the solar system — it is only a little larger than Earth's moon. Mercury zips around the sun in only 88 days and because it is so close to our star (about two-fifths the distance between Earth and the sun).Mercury experiences dramatic changes in its day and night temperatures. Mercury temperatures can reach a scorching 840 F (450 C) in the day, which is hot enough to melt lead. Meanwhile, on the night side, temperatures drop to minus 290 F (minus 180 C).  ",
    },
    {
      "id": 2,
      "name": "Venus",
      "color": "Yellow - White",
      "Discovery": "Known to the ancient Greeks and visible to the naked eye",
      "Diameter": "12,104 Km",
      "Orbit": "225 Earth Days",
      "Day": "241 Earth Days",
      "Number of moons": "0",
      "Distance from Sun": "108 Million Km",
      "Volume": "9.28415 x 1011km3",
      "Mass": "4.8673 x 10^24kg",
      "Planet type": "Terrestrial",
      "Surface temperature": "480° C",
      "images": "images/Venus.png",
      "Discription":
          "It's a cloud-swaddled planet named for a love goddess, often called Earths twin. But pull up a bit closer, and Venus turns hellish. Our nearest planetary neighbor, the second planet from the Sun, has a surface hot enough to melt lead. The atmosphere is so thick that, from the surface, the Sun is just a smear of light.",
    },
    {
      "id": 3,
      "name": "Earth",
      "color": "Blue - Green",
      "Discovery": "originates from Die Erde the German word for the ground",
      "Diameter": "12,760 Km",
      "Orbit": "365.24 Days",
      "Day": "23 hours, 56 minutes",
      "Number of moons": "1",
      "Distance from Sun": "147.65 Million Km",
      "Volume": "1 Trillion Cubic Km",
      "Mass": "5.97 x 10^24 kg",
      "Planet type": "Giant",
      "Surface temperature": "45° C",
      "images": "images/Earth.png",
      "Discription":
          "Our home planet Earth is a rocky, terrestrial planet. It has a solid and active surface with mountains, valleys, canyons, plains and so much more. Earth is special because it is an ocean planet. Water covers 70% of Earth's surface.",
    },
    {
      "id": 4,
      "name": "Mars",
      "color": "Red Planet",
      "Discovery": "Known to the ancient Greeks and visible to the naked eye",
      "Diameter": "6,787 Km",
      "Orbit": "687 Earth Days",
      "Day": "24 hours, 37 minutes",
      "Number of moons": "2",
      "Distance from Sun": "228.59 Million Km",
      "Volume": "3389.5 Km",
      "Mass": "6.39 * 10^23 Kg",
      "Planet type": "Rocky Planet",
      "Surface temperature": "-65° C",
      "images": "images/mars.png",
      "Discription":
          "Mars is the fourth planet from the Sun - a dusty, cold, desert world with a very thin atmosphere. Mars is also a dynamic planet with seasons, polar ice caps, canyons, extinct volcanoes, and evidence that it was even more active in the past.",
    },
    {
      "id": 5,
      "name": "Jupiter",
      "color": "Red - Brown",
      "Discovery": "Known to the ancient Greeks and visible to the naked eye",
      "Diameter": "39,822 Km",
      "Orbit": "11.9 Earth Years",
      "Day": "9.8 Earth Hours",
      "Number of moons": "79",
      "Distance from Sun": "740.88 Million Km",
      "Volume": "1.43 x 10^15 Km",
      "Mass": "1.898 * 10^27 kg",
      "Planet type": "Gas Giant",
      "Surface temperature": "-110° C",
      "images": "images/Jupiter.png",
      "Discription":
          "Jupiter is called a gas giant planet. Its atmosphere is made up of mostly hydrogen gas and helium gas, like the sun. The planet is covered in thick red, brown, yellow and white clouds. The clouds make the planet look like it has stripes.",
    },
    {
      "id": 6,
      "name": "Saturn",
      "color": "Yellow - Brown",
      "Discovery": "Known to the ancient Greeks and visible to the naked eye",
      "Diameter": "120,500 Km",
      "Orbit": "29.5 Earth Years",
      "Day": "About 10.5 Earth Hours",
      "Number of moons": "82",
      "Distance from Sun": "1.4707 Billion Km",
      "Volume": "8.27 x 10^14 Km",
      "Mass": "5.683 * 10^26 kg",
      "Planet type": "Gas-Giant Planet",
      "Surface temperature": "-140° C",
      "images": "images/Saturn.png",
      "Discription":
          "Saturn is the sixth planet from the Sun and the second-largest planet in our solar system. Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium. Saturn is not the only planet to have rings, but none are as spectacular or as complex as Saturn's. Saturn also has dozens of moons.",
    },
    {
      "id": 7,
      "name": "Uranus",
      "color": "Blue - Green",
      "Discovery":
          "781 by William Herschel (was originally thought to be a star)",
      "Diameter": "51,120 Km",
      "Orbit": "84 Earth Years",
      "Day": "18 Earth Hours",
      "Number of moons": "27",
      "Distance from Sun": "2.9424 Billion Km",
      "Volume": "6.83x10^13 cCubic Km",
      "Mass": "48.681 * 10^25 kg",
      "Planet type": "Ice Giant",
      "Surface temperature": "-195° C",
      "images": "images/URANUS.png",
      "Discription":
          "Uranus is made of water, methane, and ammonia fluids above a small rocky center. Its atmosphere is made of hydrogen and helium like Jupiter and Saturn, but it also has methane. The methane makes Uranus blue. Uranus also has faint rings.",
    },
    {
      "id": 8,
      "name": "Neptune",
      "color": "Blue Color",
      "Discovery": "1846",
      "Diameter": "49,530 Km",
      "Orbit": "165 Earth Years",
      "Day": "19 Earth hours",
      "Number of moons": "14",
      "Distance from Sun": "4.4737 Billion Km",
      "Volume": "1.024 * 10^26 Km",
      "Mass": "1.024 * 10^26 Kg",
      "Planet type": "Ice Giant",
      "Surface temperature": "-200° C",
      "images": "images/Neptune.png",
      "Discription":
          "Neptune is very similar to Uranus. It's made of a thick soup of water, ammonia, and methane over an Earth-sized solid center. Its atmosphere is made of hydrogen, helium, and methane. The methane gives Neptune the same blue color as Uranus.",
    },
  ];
}
